openapi: 3.0.0
info:
  title: 通用API
  version: '1.0'
  description: 通用api
servers:
  - url: 'https://global-api-sandbox.lianlianpay-inc.com/common/v1'
    description: 沙盒环境地址
  - url: 'https://global-api.lianlianglobal.com/common/v1'
    description: 生产环境地址
paths:
  /verification-codes:
    post:
      summary: 获取短信验证码
      operationId: post-verification-codes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  $ref: ./models/verification-code-enum.v1.yaml
      description: 获取短信校验码，用于相关接口做二次验证，例如：提现、供应商付款等
      tags:
        - 通用
components:
  schemas:
    bank-info:
      title: 银行信息
      type: object
      description: 国内各银行信息
      properties:
        id:
          type: string
          description: 银行信息键值
        name:
          type: string
          description: 银行名称，例如：中国银行
        branchName:
          type: string
          description: 支行名称
        prcptcd:
          type: string
          description: 大额行号
      x-tags:
        - Models
  securitySchemes:
    Authorization:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
        authorizationCode:
          authorizationUrl: ''
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
      description: '本接口中使用Basic Auth认证：(Authorization: Basic &lt;&lt;Basic64.encode(developerId:token)&gt;&gt;)'
