openapi: 3.0.0
paths:
  /common/v1/verification-codes:
    post:
      summary: 获取短信验证码
      operationId: post-verification-codes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  $ref: '#/components/schemas/verification-code-enum'
      description: 获取短信校验码，用于相关接口做二次验证，例如：提现、供应商付款等
      tags:
        - 通用
    parameters: []
  '/common/v1/dictionaries/district/{code}':
    parameters:
      - schema:
          type: string
        name: code
        in: path
        required: true
    get:
      summary: 省市字典接口
      tags:
        - 通用
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/district'
      operationId: get-dictionaries-district-code
      description: 获取省市字典，根code请填写 `CHN`
components:
  schemas:
    district:
      title: 省市区编码
      type: object
      properties:
        name:
          type: string
          description: 名称
          example: 中国
        code:
          type: string
          description: 编码
          example: CNH
      required:
        - code
        - name
      x-tags:
        - Models
    verification-code-enum:
      type: string
      title: 校验码枚举
      enum:
        - WITHDRAW_COMBINE
        - SUPPLIER_PAYMENT
      example: WITHDRAW_COMBINE
      description: |-
        | Value | Description |
        |--------|------------|
        | WITHDRAW_COMBINE| 提现校验码 |
        | SUPPLIER_PAYMENT | 供应商付款校验码 |
      x-tags:
        - Models
    attachment:
      title: 附件对象
      type: object
      properties:
        id:
          type: string
          description: Document id in Lianlian Pay system
        name:
          type: string
          description: Document name
        size:
          type: integer
          description: Document size
        create_time:
          type: string
          format: date-time
          description: 'Document create time, UTC+0 timestamp'
      description: 附件接口
      x-tags:
        - 通用
  securitySchemes:
    Authorization:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
        authorizationCode:
          authorizationUrl: ''
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
      description: '本接口中使用Basic Auth认证：(Authorization: Basic &lt;&lt;Basic64.encode(developerId:token)&gt;&gt;)'
info:
  title: 5. 通用服务
  version: '1.0'
  description: ''
servers:
  - url: 'https://global-api-sandbox.lianlianpay-inc.com'
    description: 沙盒环境地址
  - url: 'https://global-api.lianlianglobal.com'
    description: 生产环境地址
