openapi: 3.0.0
paths:
  /common/v1/verification-codes:
    post:
      summary: 获取短信验证码
      operationId: post-verification-codes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  $ref: '#/components/schemas/verification-code-enum'
      description: 获取短信校验码，用于相关接口做二次验证，例如：提现、供应商付款等
      tags:
        - 通用
    parameters: []
  '/common/v1/dictionaries/district/{code}':
    parameters:
      - schema:
          type: string
        name: code
        in: path
        required: true
    get:
      summary: 省市字典接口
      tags:
        - 通用
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/district'
      operationId: get-dictionaries-district-code
      description: 获取省市字典，根code请填写 `CHN`
  /documents:
    post:
      summary: 1. Upload Document
      operationId: post-documents
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '400':
          description: "Bad Request\n\nPossible error codes:\n\n| Code | Description |\n|------|-------------|\n| 510002 | Unsupported document type. |\n| 999995 | \\[PARAMETER\\] ERROR_MESSAGE |\n"
        '500':
          description: Internal Server Error
      description: "Upload document to Lianlian Pay system. \n\n**This method will be hosted in both US and CN**, support document(s) for US profiles should be uploaded via US endpoint and supported document(s) for CN/HK profiles should be uploaded via CN endpoint. \n\n| environment | endpoint |\n|-------------|----------|\n| US Sandbox | https://global-api-us-sandbox.lianlianpay-inc.com/escrow/v1 |\n| US Production | https://global-api-us.lianlianpay.com/escrow/v1 |\n| CN Sandbox |https://global-api-sandbox.lianlianpay-inc.com/escrow/v1 |\n| CN Production | https://global-api.lianlianpay.com/escrow/v1 |\n\nLianlian Pay system supported document types are **PDF**, **JPG**, **JPEG** and **PNG**.\n\nReturn type is `Document` object. `Document.id` should be used in other APIs if a support document is required."
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Document name(including extension)
                  maxLength: 128
              required:
                - name
            examples: {}
        description: ''
      tags:
        - Documents
components:
  schemas:
    district:
      title: 省市区编码
      type: object
      properties:
        name:
          type: string
          description: 名称
          example: 中国
        code:
          type: string
          description: 编码
          example: CNH
      required:
        - code
        - name
      x-tags:
        - Models
    verification-code-enum:
      type: string
      title: 校验码枚举
      enum:
        - WITHDRAW_COMBINE
        - SUPPLIER_PAYMENT
      example: WITHDRAW_COMBINE
      description: |-
        | Value | Description |
        |--------|------------|
        | WITHDRAW_COMBINE| 提现校验码 |
        | SUPPLIER_PAYMENT | 供应商付款校验码 |
      x-tags:
        - Models
    attachment:
      title: 附件对象
      type: object
      properties:
        id:
          type: string
          description: Document id in Lianlian Pay system
        create_time:
          type: string
          format: date-time
          description: 'Document create time, UTC+0 timestamp'
        size:
          type: integer
          description: Document size
        name:
          type: string
          description: Document name
      x-tags:
        - 通用
      description: 附件接口
  securitySchemes:
    Authorization:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
        authorizationCode:
          authorizationUrl: ''
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
      description: '本接口中使用Basic Auth认证：(Authorization: Basic &lt;&lt;Basic64.encode(developerId:token)&gt;&gt;)'
info:
  title: 6. 通用服务
  version: '1.0'
  description: ''
servers:
  - url: 'https://global-api-sandbox.lianlianpay-inc.com'
    description: 沙盒环境地址
  - url: 'https://global-api.lianlianglobal.com'
    description: 生产环境地址
