openapi: 3.0.0
info:
  title: 1. 店铺服务
  version: '1.0'
  description: ''
servers:
  - url: 'https://global-api-sandbox.lianlianpay-inc.com'
    description: Sandbox
  - url: 'https://global-api.lianlianpay.com'
    description: Production
paths:
  /collection /v1/shops:
    get:
      summary: 查询店铺列表
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  list:
                    type: array
                    items:
                      $ref: '#/components/schemas/ShopInfo'
                required:
                  - total
                  - list
      operationId: get-shops
      description: 根据平台类型和地区查询店铺列表，结果按更新时间排序。
      requestBody: {}
      parameters:
        - schema:
            type: string
            enum: []
          in: query
          name: platform
          description: |-
            平台类型

            platform|name
            -|-
            Amazon|亚马逊
            FBA|亚马逊印度站（FBA）
            PAYPAL|PayPal
            SHOPEE|SHOPEE
            SOUQ|SOUQ
            CDiscount|Cdiscount
            Mercado|Mercadolibre
            JDID|JD.ID(USD)
            JDIDIDR|JD.ID
            Rakuten|法国乐天
            DeRakuten|德国乐天
            BRINGLY|bringly
            FNAC|fnac
            SHOPIFY|Shopify
            FRUUGO|fruugo
            SELF_BUILD|自建站
            QOO10|Qoo10
            APPSTORE|AppStore
            ALIEXPRESS|AliExpress
            BIGCOMMERCE|Bigcommerce
            MAGENTO|Magento
            NOON|Noon
            REAL_DE|real.de
            MEESHO|Meesho
            ALLEGRO|Allegro
            ALLEGRO_PLN|Allegro
            COUPANG|Coupang
            DARTY|Darty
            VOVA|Vova
            B2W|B2W
            ADSENSE|AdSense
            ADMOB|AdMob
            WIX|Wix
            GOOGLE_SHOPPING_ACTIONS|Google Shopping Actions
            EMAG|eMAG
        - schema:
            type: string
          in: query
          name: region
          description: |-
            地区

            |region|
            |-|
            |US|
            |EU|
            |JP|
            |AU|
            |AE|
            |IN|
            |MY|
            |ID|
            |TW|
            |TH|
            |PH|
            |SG|
            |HK|
            |KR|
        - schema:
            type: integer
            default: 1
          in: query
          name: pageNum
          description: 页码
          required: true
        - schema:
            type: integer
            maximum: 100
            minimum: 1
          in: query
          name: pageSize
          description: 分页大小
          required: true
      tags:
        - 接口
    parameters: []
components:
  schemas:
    ShopInfo:
      title: 店铺信息对象
      type: object
      description: ''
      properties:
        platformId:
          type: string
          description: 平台id
        platform:
          type: string
          description: 平台类型
        sellerId:
          type: string
          description: 卖家编号
        id:
          type: string
          description: 店铺id
        shopName:
          type: string
          description: 店铺名称
        status:
          type: integer
          description: |-
            状态

            status|message
            -|-
            0|待完善信息
            1|待审核
            2|审核通过
            3|审核失败
            4|注销
            5|已迁移
            6|未激活
        region:
          type: string
          description: 地区
        accountInfo:
          type: object
          description: 收款银行账号信息
          required:
            - accountId
            - virtualAccount
            - currency
            - accountName
            - region
            - bankName
            - appendInfo
          properties:
            accountId:
              type: string
              description: 账号id
            virtualAccount:
              type: string
              description: 虚拟账号
            currency:
              type: string
              description: 币种
            accountName:
              type: string
              description: 户名
            region:
              type: string
              description: 银行地区
            bankName:
              type: string
              description: 银行名称
            appendInfo:
              type: string
              description: 银行账号附加信息
        createTime:
          type: string
          description: 创建时间
        modifyTime:
          type: string
          description: 更新时间
      required:
        - platformId
        - platform
        - sellerId
        - id
        - shopName
        - status
        - region
        - accountInfo
        - createTime
        - modifyTime
      x-tags:
        - 对象
