openapi: 3.0.0
info:
  title: 4. 供应商付款服务
  version: '1.0'
  description: 供应商付款api
servers:
  - url: 'https://global-api-sandbox.lianlianpay-inc.com'
    description: 沙盒环境地址
  - description: 生产环境地址
    url: 'https://global-api.lianlianglobal.com'
paths:
  '/supplier/v1/batch-payments/{batchId}/payments':
    parameters:
      - schema:
          type: string
        name: batchId
        in: path
        required: true
    get:
      summary: 查询付款明细
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                  list:
                    type: array
                    items:
                      $ref: '#/components/schemas/payment'
      operationId: get-batch-pays-extBatchId
      description: 获取批量付款明细
      requestBody:
        description: ''
      parameters:
        - schema:
            type: string
          in: query
          name: paymentId
        - schema:
            type: integer
            maximum: 100
            minimum: 1
          in: query
          name: pageSize
          required: true
          description: 分页大小
        - schema:
            type: number
            minimum: 1
          in: query
          name: pageNum
          description: 页码
          required: true
      tags:
        - 付款
  /supplier/v1/batch-payments:
    get:
      summary: 查询批量付款结果
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/batch-payment'
      operationId: get-pays
      description: 查询批量付款结果信息
      requestBody: {}
      parameters:
        - schema:
            type: string
          in: query
          name: batchId
          required: true
          description: 批量付款批次号
      tags:
        - 付款
    post:
      summary: 创建批量付款请求
      operationId: post-pays
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/batch-payment'
      description: |+
        1、该接口的调用需要优先在连连端开通功能白名单方可使用；

        2、在创建该请求前用户需要先调用短信验证码接口来获取二次校验，短信验证码错误次数达8次账号锁定且在2小时之内不能再进行资金操作（当连连这边认定的假期期间，供应商付款也是暂时不可用的）；

        3、当用户发送批量付款请求时，API端会根据当前汇率来预估用户余额是否充足，如果余额不足会返回余额不足错误。


      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                batchId:
                  type: string
                  minLength: 16
                  maxLength: 32
                  description: 付款批次号
                verificationCode:
                  type: string
                  description: 短信验证码
                  minLength: 4
                  maxLength: 8
                sourceCurrency:
                  type: string
                  description: 源币种
                  example: USD
                  minLength: 3
                  maxLength: 3
                targetCurrency:
                  type: string
                  description: 目标币种
                  example: USD
                  minLength: 3
                  maxLength: 3
                list:
                  type: object
                  description: 批量付款总笔数，最大5000条
                  required:
                    - tradeCode
                    - payeeBankAccountId
                    - payeeBankAccountNo
                    - paymentId
                    - tradeDate
                    - goodsName
                    - goodsNumber
                    - goodsPrice
                    - logistics
                    - procurementType
                    - targetAmount
                  maxProperties: 1000
                  properties:
                    tradeCode:
                      type: string
                      description: "    E_BUSINESS(电商销售/货物贸易)\n    LOGISTIC_FEE(物流费)"
                      enum:
                        - E_BUSINESS
                        - LOGISTIC_FEE
                    payeeBankAccountId:
                      type: string
                      description: 收款人编号
                      maxLength: 32
                    payeeBankAccountNo:
                      type: string
                      description: 收款人银行账号，用于校验
                      maxLength: 32
                    paymentId:
                      type: string
                      description: 外部唯一单号
                      maxLength: 32
                    tradeDate:
                      type: string
                      default: yyyy-MM-dd
                      description: 交易时间
                      format: date
                    goodsName:
                      type: string
                      description: 商品名称
                      maxLength: 64
                    goodsNumber:
                      type: integer
                      description: 商品数量
                      exclusiveMaximum: false
                    goodsPrice:
                      type: number
                      description: 商品单价
                      minimum: 0
                    logistics:
                      type: string
                      description: "    EXPRESS(快递)\n    OFFLINE(当面采购)\n    LOGISTICS(物流)"
                      enum:
                        - EXPRESS
                        - OFFLINE
                        - LOGISTICS
                    procurementType:
                      type: string
                      description: "    ONLINE(网络采购)\n    OFFLINE_HAS_TAX(线下有票(增值税发票))\n    OFFLINE_NO_TAX(线下无票(无增值税发票))"
                      enum:
                        - ONLINE
                        - OFFLINE_HAS_TAX
                        - OFFLINE_NO_TAX
                    targetAmount:
                      type: string
                      description: 目标金额
              required:
                - batchId
                - verificationCode
                - sourceCurrency
                - targetCurrency
                - list
        description: ''
      tags:
        - 付款
    parameters: []
components:
  schemas:
    payment:
      title: 付款指令对象
      type: object
      description: 付款指令信息
      properties:
        paymentId:
          type: string
          description: 外部流水号
        payeeBankAccountId:
          type: string
          description: 收款人id
        sourceCurrency:
          type: string
          description: 源币种
        sourceAmount:
          type: string
          description: 源金额
        targetCurrency:
          type: string
          description: 目标币种
        targetAmount:
          type: string
          description: 目标金额
        tradeCode:
          type: string
          description: 贸易类型
        tradeDate:
          type: string
          description: 交易时间
        goodsName:
          type: string
          description: 商品名称
        goodsNumber:
          type: string
          description: 商品数量
        goodsPrice:
          type: string
          description: 商品单价
        logistics:
          type: string
          description: 物流方式
        procurementType:
          type: string
          description: 采购类型
        status:
          type: string
          description: "    ON_GOING(\"付款中\"),\n    SUCCESS(\"付款成功\"),\n    FAILED(\"付款失败\"),\n    EXTERNAL_CHECKING(\"审核中\")"
          enum:
            - ON_GOING
            - SUCCESS
            - FAILED
            - REFUNDING
            - REFUNDED
            - CANCELED
            - EXTERNAL_CHECKIGN
        failedReason:
          type: string
          description: 失败原因
        rate:
          type: string
          description: 汇率
        rateTime:
          type: string
          description: 汇率时间
        commissionReceived:
          type: string
          description: 实收手续费（源币种）
        refundAmount:
          type: string
          description: 退款金额（源币种，当退汇时有该金额）
        createTime:
          type: string
          description: 付款单创建时间
      x-tags:
        - Models
    batch-payment:
      title: 批量付款对象
      type: object
      description: 批次付款object
      properties:
        createTime:
          type: string
          description: 创建时间
        batchId:
          type: string
          description: 批次号
        total:
          type: string
          description: 批次请求总数
        targetCurrency:
          type: string
          description: 目标币种
        targetAmount:
          type: string
          description: 目标金额
        payingTotal:
          type: string
          description: 付款中笔数
        paidTotal:
          type: string
          description: 已付款笔数
        failedTotal:
          type: string
          description: 失败笔数
      x-tags:
        - Models
  securitySchemes:
    Authorization:
      type: oauth2
      description: '本接口中使用Basic Auth认证：(Authorization: Basic &lt;&lt;Basic64.encode(developerId:token)&gt;&gt;)'
      flows:
        clientCredentials:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
        authorizationCode:
          authorizationUrl: ''
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
