openapi: 3.0.0
info:
  title: 供应商付款API
  version: '1.0'
  description: 供应商付款api
servers:
  - url: 'https://global-api-sandbox.lianlianpay-inc.com/supplier/v1'
    description: 沙盒环境地址
  - description: 生产环境地址
    url: 'https://global-api.lianlianglobal.com/supplier/v1'
paths:
  /cards:
    get:
      summary: 查询多比充值账号信息
      operationId: get-cards
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/card.v1.yaml
      description: 根据币种获取卡信息
      requestBody:
        description: ''
      parameters:
        - schema:
            type: string
          in: query
          name: currency
          required: true
      tags:
        - 卡
  /card-recharges:
    get:
      summary: 查询银行转入记录
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                    description: 总数
                  list:
                    type: array
                    description: 充值记录
                    minItems: 0
                    items:
                      $ref: ./models/card-recharge-info.v1.yaml
                required:
                  - total
                  - list
      operationId: get-cards-recharges
      description: 查询虚拟卡充值记录
      requestBody:
        description: ''
      parameters:
        - schema:
            type: string
          in: query
          name: currency
          description: 币种
        - schema:
            type: string
          in: query
          name: startTime
          description: 开始时间
          required: true
        - schema:
            type: string
          in: query
          name: endTime
          description: 结束时间
          required: true
        - schema:
            type: string
          in: query
          name: accountNumber
          description: 卡号
          required: true
        - schema:
            type: integer
            minimum: 1
            maximum: 100
          in: query
          name: pageSize
          description: 分页大小
          required: true
        - schema:
            type: integer
            default: 0
            maximum: 0
            minimum: 1
          in: query
          name: pageNumber
          description: 页码
          required: true
      tags:
        - 卡
    parameters: []
  /payee-bank-accounts:
    post:
      summary: 创建收款人银行卡信息
      operationId: post-payees
      responses:
        '200':
          description: OK
      description: |-
        创建收款人银行卡信息：
          创建收款人银行卡信息分为两种：1、创建国内CNY（人民币）银行卡，这时候你需要传cnyBankInfo必传
                                      2、创建外币银行卡，这时候foreignBankInfo必传
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                payeeBankAccountId:
                  type: string
                  description: 外部收款人银行卡账户编号
                  maxLength: 32
                attachmentId:
                  type: string
                  description: 附件编号
                  maxLength: 32
                accountType:
                  type: string
                  enum:
                    - ENTERPRISE
                    - INDIVIDUAL
                  description: |-
                    银行卡账户绑定类型：
                       ENTERPRISE: 对公类型
                       INDIVIDUAL: 对私类型
                region:
                  type: string
                  description: "    CN(\"CN\", \"中国大陆\"),\n    US(\"US\", \"美国\"),\n    FR(\"FR\", \"法国\"),\n    DE(\"DE\", \"德国\"),\n    IT(\"IT\", \"意大利\"),\n    ES(\"ES\", \"西班牙\"),\n    GB(\"GB\", \"英国\"),\n    HK(\"HK\", \"中国香港\"),\n    AU(\"AU\", \"澳大利亚\"),\n    TW(\"TW\", \"中国台湾\"),\n    KR(\"KR\", \"韩国\"),\n    JP(\"JP\", \"日本\")"
                  enum:
                    - CN
                    - US
                    - FR
                    - DE
                    - IT
                    - ES
                    - GB
                    - HK
                  minLength: 2
                  maxLength: 2
                cnyBankInfo:
                  $ref: ./models/CNY-bank-info.v1.yaml
                foreignBankInfo:
                  $ref: ./models/foreign-bank-info.v1.yaml
              required:
                - payeeBankAccountId
                - attachmentId
                - accountType
                - region
                - cnyBankInfo
                - foreignBankInfo
        description: ''
      tags:
        - 收款人
    get:
      summary: 查询收款人银行卡信息
      operationId: get-payees
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/payee-bank-account.v1.yaml
      description: 查询收款人信息
      requestBody:
        description: ''
      parameters:
        - schema:
            type: string
          in: query
          name: payeeBankAccountId
          required: true
          description: 收款人银行卡账户号
      tags:
        - 收款人
    delete:
      summary: 删除收款人银行卡信息
      operationId: delete-payees
      description: 根据收款人银行卡id删除收款人银行卡信息
      requestBody: {}
      parameters:
        - schema:
            type: string
          in: query
          name: payeeBankAccountId
          required: true
          description: 收款人银行卡账户号
      tags:
        - 收款人
    parameters: []
  /batch-payments:
    get:
      summary: 获取批量付款结果
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/batch-pay.v1.yaml
      operationId: get-pays
      description: 查询批量付款结果信息
      requestBody: {}
      parameters:
        - schema:
            type: string
          in: query
          name: batchId
          required: true
          description: 批量付款批次号
      tags:
        - 付款
    post:
      summary: 创建批量付款请求
      operationId: post-pays
      responses:
        '200':
          description: OK
      description: 创建付款指令
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                batchId:
                  type: string
                  description: 外部批次号
                verificationCode:
                  type: string
                  description: 短信验证码
                sourceCurrency:
                  type: string
                  description: 源币种
                targetCurrency:
                  type: string
                  description: 目标币种
                list:
                  type: object
                  properties:
                    tradeCode:
                      type: string
                      description: "    电商销售/货物贸易\n    物流费"
                    payeeBankAccountId:
                      type: string
                      description: 收款人编号
                    payeeBankAccountNumber:
                      type: string
                      description: 收款人银行卡号，用于校验
                    paymentId:
                      type: string
                      description: 外部唯一单号
                    tradeDate:
                      type: string
                      default: yyyy-MM-dd
                      description: 交易时间
                      format: date
                    goodsName:
                      type: string
                      description: 商品名称
                    goodsNumber:
                      type: string
                      description: 商品数量
                    goodsPrice:
                      type: string
                      description: 商品单价
                    logistics:
                      type: string
                      description: "    快递\n    当面采购\n    物流"
                    procurementType:
                      type: string
                      description: "    网络采购\n    线下有票(增值税发票)\n    线下无票(无增值税发票)"
                    tragetAmount:
                      type: string
                      description: 目标金额
                  required:
                    - tradeCode
                    - payeeBankAccountId
                    - payeeBankAccountNumber
                    - paymentId
                    - tradeDate
                    - goodsName
                    - goodsNumber
                    - goodsPrice
                    - logistics
                    - procurementType
              required:
                - batchId
                - sourceCurrency
                - targetCurrency
        description: ''
      tags:
        - 付款
    parameters: []
  '/batch-payments/{batchId}/payments':
    parameters:
      - schema:
          type: string
        name: batchId
        in: path
        required: true
    get:
      summary: 获取付款明细
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                  list:
                    type: array
                    items:
                      $ref: ./models/payment.v1.yaml
      operationId: get-batch-pays-extBatchId
      description: 获取批量付款明细
      requestBody:
        description: ''
      parameters:
        - schema:
            type: string
          in: query
          name: paymentId
        - schema:
            type: integer
            maximum: 100
            minimum: 1
          in: query
          name: pageSize
          required: true
          description: 分页大小
        - schema:
            type: integer
            maximum: 0
            minimum: 1
          in: query
          name: pageNum
          required: true
          description: 页码
      tags:
        - 付款
  /payee-document:
    put:
      summary: 更新收款人材料信息
      operationId: put-payee-document
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                payeeBankAccountId:
                  type: string
                  description: 外部收款人银行账户id
                attatchmentId:
                  type: string
                  description: 附件id
        description: ''
      description: 更新材料信息，更新材料信息后用户材料状态变成待审核状态，审核成功之后即可使用
      tags:
        - 收款人
components:
  schemas: {}
  securitySchemes:
    Authorization:
      type: oauth2
      description: '本接口中使用Basic Auth认证：(Authorization: Basic &lt;&lt;Basic64.encode(developerId:token)&gt;&gt;)'
      flows:
        clientCredentials:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
        authorizationCode:
          authorizationUrl: ''
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
