openapi: 3.0.0
info:
  title: 供应商付款API
  version: '1.0'
  description: 供应商付款api
servers:
  - url: 'https://global-api-sandbox.lianlianpay-inc.com/supplier/v1'
    description: 沙盒环境地址
  - description: 生产环境地址
    url: 'https://global-api.lianlianglobal.com/supplier/v1'
paths:
  /cards:
    get:
      summary: 查询多比充值账号信息
      operationId: get-cards
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/card.v1.yaml
      description: 根据币种获取卡信息
      requestBody:
        description: ''
      parameters:
        - schema:
            type: string
          in: query
          name: currency
          required: true
      tags:
        - 卡
  /card-recharges:
    get:
      summary: 查询银行转入记录
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                    description: 总数
                  list:
                    type: array
                    description: 充值记录
                    minItems: 0
                    items:
                      $ref: ./models/card-recharge-info.v1.yaml
                required:
                  - total
                  - list
      operationId: get-cards-recharges
      description: 查询虚拟卡充值记录
      requestBody:
        description: ''
      parameters:
        - schema:
            type: string
          in: query
          name: currency
          description: 币种
        - schema:
            type: string
          in: query
          name: startTime
          description: 开始时间
          required: true
        - schema:
            type: string
          in: query
          name: endTime
          description: 结束时间
          required: true
        - schema:
            type: string
          in: query
          name: accountNo
          description: 卡号
          required: true
        - schema:
            type: integer
            minimum: 1
            maximum: 100
          in: query
          name: pageSize
          description: 分页大小
          required: true
        - schema:
            type: integer
            default: 0
            maximum: 0
            minimum: 1
          in: query
          name: pageNumber
          description: 页码
          required: true
      tags:
        - 卡
    parameters: []
  /batch-payments:
    get:
      summary: 获取批量付款结果
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/batch-pay.v1.yaml
      operationId: get-pays
      description: 查询批量付款结果信息
      requestBody: {}
      parameters:
        - schema:
            type: string
          in: query
          name: batchId
          required: true
          description: 批量付款批次号
      tags:
        - 付款
    post:
      summary: 创建批量付款请求
      operationId: post-pays
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/batch-pay.v1.yaml
      description: |+
        1、该接口的调用需要优先在连连端开通功能白名单方可使用；

        2、在创建该请求前用户需要先调用短信验证码接口来获取二次校验，短信验证码错误次数达8次账号锁定且在2小时之内不能再进行资金操作（当连连这边认定的假期期间，供应商付款也是暂时不可用的）；

        3、当用户发送批量付款请求时，API端会根据当前汇率来预估用户余额是否充足，如果余额不足会返回余额不足错误。


      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                batchId:
                  type: string
                  minLength: 16
                  maxLength: 32
                  description: 付款批次号
                verificationCode:
                  type: string
                  description: 短信验证码
                  minLength: 4
                  maxLength: 8
                sourceCurrency:
                  type: string
                  description: 源币种
                  example: USD
                  minLength: 3
                  maxLength: 3
                targetCurrency:
                  type: string
                  description: 目标币种
                  example: USD
                  minLength: 3
                  maxLength: 3
                list:
                  type: object
                  description: 批量付款总笔数，最大5000条
                  required:
                    - tradeCode
                    - payeeBankAccountId
                    - payeeBankAccountNo
                    - paymentId
                    - tradeDate
                    - goodsName
                    - goodsNumber
                    - goodsPrice
                    - logistics
                    - procurementType
                    - targetAmount
                  maxProperties: 1000
                  properties:
                    tradeCode:
                      type: string
                      description: "    E_BUSINESS(电商销售/货物贸易)\n    LOGISTIC_FEE(物流费)"
                      enum:
                        - E_BUSINESS
                        - LOGISTIC_FEE
                    payeeBankAccountId:
                      type: string
                      description: 收款人编号
                      maxLength: 32
                    payeeBankAccountNo:
                      type: string
                      description: 收款人银行卡号，用于校验
                      maxLength: 32
                    paymentId:
                      type: string
                      description: 外部唯一单号
                      maxLength: 32
                    tradeDate:
                      type: string
                      default: yyyy-MM-dd
                      description: 交易时间
                      format: date
                    goodsName:
                      type: string
                      description: 商品名称
                      maxLength: 64
                    goodsNumber:
                      type: integer
                      description: 商品数量
                      exclusiveMaximum: false
                    goodsPrice:
                      type: number
                      description: 商品单价
                      minimum: 0
                    logistics:
                      type: string
                      description: "    EXPRESS(快递)\n    OFFLINE(当面采购)\n    LOGISTICS(物流)"
                      enum:
                        - EXPRESS
                        - OFFLINE
                        - LOGISTICS
                    procurementType:
                      type: string
                      description: "    ONLINE(网络采购)\n    OFFLINE_HAS_TAX(线下有票(增值税发票))\n    OFFLINE_NO_TAX(线下无票(无增值税发票))"
                      enum:
                        - ONLINE
                        - OFFLINE_HAS_TAX
                        - OFFLINE_NO_TAX
                    targetAmount:
                      type: string
                      description: 目标金额
              required:
                - batchId
                - verificationCode
                - sourceCurrency
                - targetCurrency
                - list
        description: ''
      tags:
        - 付款
    parameters: []
  '/batch-payments/{batchId}/payments':
    parameters:
      - schema:
          type: string
        name: batchId
        in: path
        required: true
    get:
      summary: 获取付款明细
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                  list:
                    type: array
                    items:
                      $ref: ./models/payment.v1.yaml
      operationId: get-batch-pays-extBatchId
      description: 获取批量付款明细
      requestBody:
        description: ''
      parameters:
        - schema:
            type: string
          in: query
          name: paymentId
        - schema:
            type: integer
            maximum: 100
            minimum: 1
          in: query
          name: pageSize
          required: true
          description: 分页大小
        - schema:
            type: number
            minimum: 1
          in: query
          name: pageNum
          description: 页码
          required: true
      tags:
        - 付款
  /payee-document:
    put:
      summary: 更新收款人材料信息
      operationId: put-payee-document
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                payeeBankAccountId:
                  type: string
                  description: 外部收款人银行账户id
                attachmentId:
                  type: string
                  description: 附件id
        description: ''
      description: 更新材料信息，更新材料信息后用户材料状态变成待审核状态，审核成功之后即可使用
      tags:
        - 收款人
  /payee-bank-accounts:
    post:
      summary: 创建收款人银行卡信息
      operationId: post-payees
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/payee-bank-account.v1.yaml
          headers: {}
        '400':
          description: |-
            业务失败:

            | Code | Description |
            |------|------------|
            | 999995| 参数校验失败 |
            | 510004| 附件不存在 |
            | 009012| 该银行卡企业“贸易外汇收支企业名录”状态异常，无法提现至该银行卡 |
            | 009013| 该银行卡企业未在当地外管局办理名录登记，无法提现至该银行卡 |
            | 109001| 收款人申报失败 |
            | 109002| 收款人审核失败 |
            | 109003| 对公账户不支持绑定对私银行卡 |
            | 109004| 存在待审核的合同 |
            | 109002| 收款人信息有误 |
        '500':
          description: |-
            系统异常类型:

            | Code | Description |
            |------|------------|
            | 500000| Internal Server Error, Contact Lianlian Pay for technical support|
      description: |-
        创建收款人银行卡信息，创建前请提前调用附件接口上传相关材料文件，创建成功会返回收款人信息，如果姓名、证件号、银行卡匹配已有收款人信息，则会返回已存在的收款人。

        成功创建收款人银行卡之后，连连这边会给与审核，状态为审核成功之后就能正常使用该收款人。

        收款银行编码请参照 `银行信息枚举` 对象
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                attachmentId:
                  type: string
                  description: 附件编号（调用附件上传接口获得）
                  maxLength: 32
                accountType:
                  type: string
                  enum:
                    - ENTERPRISE
                    - INDIVIDUAL
                  description: |-
                    银行卡账户绑定类型：
                       ENTERPRISE: 对公类型
                       INDIVIDUAL: 对私类型
                region:
                  type: string
                  description: "    CN(\"CN\", \"中国大陆\"),\n    US(\"US\", \"美国\"),\n    FR(\"FR\", \"法国\"),\n    DE(\"DE\", \"德国\"),\n    IT(\"IT\", \"意大利\"),\n    ES(\"ES\", \"西班牙\"),\n    GB(\"GB\", \"英国\"),\n    HK(\"HK\", \"中国香港\"),\n    AU(\"AU\", \"澳大利亚\"),\n    TW(\"TW\", \"中国台湾\"),\n    KR(\"KR\", \"韩国\"),\n    JP(\"JP\", \"日本\")"
                  enum:
                    - CN
                    - US
                    - FR
                    - DE
                    - IT
                    - ES
                    - GB
                    - HK
                    - AU
                    - TW
                    - KR
                    - JP
                  minLength: 2
                  maxLength: 2
                cnyBankAccountInfo:
                  type: object
                  description: 人民币银行账户
                  properties:
                    contactPhone:
                      type: string
                      description: 收款人联系电话
                      maxLength: 12
                    accountNo:
                      type: string
                      description: 银行卡号
                      maxLength: 32
                    certNo:
                      type: string
                      maxLength: 18
                      description: '收款人证件号码:对公时为企业信用代码；对私为个人身份证号码'
                    branchBankName:
                      type: string
                      description: 支行名称
                      maxLength: 32
                    accountName:
                      type: string
                      description: 账户名称
                      maxLength: 32
                    bankCode:
                      type: number
                      description: 银行编号，请参照`银行枚举信息`对象填写编号
                      minimum: 1
                      maximum: 288
                    cityCode:
                      type: string
                      description: '城市编码,请根据`省市字典接口`查询'
                  required:
                    - contactPhone
                    - accountNo
                    - certNo
                    - branchBankName
                    - accountName
                    - bankCode
                    - cityCode
                noneCNYBankAccountInfo:
                  $ref: ./models/foreign-bank-info.v1.yaml
              required:
                - attachmentId
                - accountType
                - region
        description: "  创建收款人银行卡信息分为两种：\n  \n  1、创建国内CNY（人民币）银行卡，这时候你需要传cnyBankInfo必传\n  \n  \n  2、创建外币银行卡，这时候foreignBankInfo必传"
      tags:
        - 收款人
    parameters: []
    get:
      summary: 分页查询收款人信息
      operationId: get-payee-bank-accounts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                    description: 总大小
                  list:
                    type: array
                    items:
                      $ref: ./models/payee-bank-account.v1.yaml
                required:
                  - total
        '400':
          description: |-
            业务失败:

            | Code | Description |
            |------|------------|
            | 999995| 参数校验失败 |
        '500':
          description: |-
            系统异常类型:

            | Code | Description |
            |------|------------|
            | 500000| Internal Server Error, Contact Lianlian Pay for technical support|
      description: 分页查询收款人信息
      parameters:
        - schema:
            type: string
          in: query
          name: id
          description: 收款人银行卡账户号
        - schema:
            type: string
          in: query
          name: region
          description: 地区
        - schema:
            type: string
          in: query
          name: accountNo
          description: 户名
        - schema:
            type: number
            example: 10
            maximum: 100
            minimum: 1
          in: query
          name: pageSize
          required: true
          description: 分页大小
        - schema:
            type: number
            minimum: 1
            example: 1
          in: query
          name: pageNum
          description: 分页页码
          required: true
      tags:
        - 收款人
  '/payee-bank-accounts/account/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    delete:
      summary: 删除收款人银行卡信息
      operationId: delete-payee-bank-accounts-account-id
      responses:
        '200':
          description: OK
      tags:
        - 收款人
      description: ''
components:
  schemas: {}
  securitySchemes:
    Authorization:
      type: oauth2
      description: '本接口中使用Basic Auth认证：(Authorization: Basic &lt;&lt;Basic64.encode(developerId:token)&gt;&gt;)'
      flows:
        clientCredentials:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
        authorizationCode:
          authorizationUrl: ''
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
