openapi: 3.0.0
info:
  title: supplier-payment
  version: '1.0'
  description: 供应商付款api
servers:
  - url: 'https://global-api-sandbox.lianlianpay-inc.com/supplier/v1'
    description: Sandbox
  - description: Production
    url: 'https://global-api.lianlianglobal.com/supplier/v1'
paths:
  /cards:
    get:
      summary: GET cards
      operationId: get-cards
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/card.v1.yaml
      description: 根据币种获取卡信息
      requestBody:
        description: ''
      parameters:
        - schema:
            type: string
          in: query
          name: currency
          required: true
  /card-recharges:
    get:
      summary: GET card recharges
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                    description: 总数
                  list:
                    type: array
                    description: 充值记录
                    minItems: 0
                    items:
                      $ref: ./models/card-recharge-info.v1.yaml
                required:
                  - total
                  - list
      operationId: get-cards-recharges
      description: 查询虚拟卡充值记录
      requestBody:
        description: ''
      parameters:
        - schema:
            type: string
          in: query
          name: currency
          description: 币种
        - schema:
            type: string
          in: query
          name: startTime
          description: 开始时间
          required: true
        - schema:
            type: string
          in: query
          name: endTime
          description: 结束时间
          required: true
        - schema:
            type: string
          in: query
          name: cardNo
          description: 卡号
        - schema:
            type: integer
            minimum: 1
            maximum: 100
          in: query
          name: pageSize
          description: 分页大小
          required: true
        - schema:
            type: integer
            default: 0
            maximum: 0
            minimum: 1
          in: query
          name: pageNumber
          description: 页码
          required: true
    parameters: []
  /payee-bank-accounts:
    post:
      summary: POST create payee bank account
      operationId: post-payees
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/payee-bank-account.v1.yaml
      description: 创建收款人
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                attachementId:
                  type: string
                  description: 附件id
                payeeInfo:
                  type: object
                  properties:
                    name:
                      type: string
                      description: 姓名
                    certType:
                      type: string
                      description: 证件类型
                    certNo:
                      type: string
                      description: 证件号码
                    type:
                      type: string
                      description: 收款人类型：公司、个人
                  required:
                    - name
                routingNumber:
                  type: string
                  description: 银行所在地为美国时必填
                sortCode:
                  type: string
                  description: '银行分类号码:银行所在地为英国时必填'
                swiftCode:
                  type: string
                  description: 银行所在地为非大陆时必填
                cardType:
                  type: string
                  description: "    DEBIT(0, \"借记卡\"),\n    CREDIT(1, \"信用卡\"),\n    CORPORATE(2, \"对公银行卡\");"
                userType:
                  type: string
                  description: "    INDIVIDUAL(\"个人\", \"0\"),\n    ENTERPRISE(\"企业\", \"1\");"
                region:
                  type: string
                  description: "    CN(\"CN\", \"中国大陆\"),\n    US(\"US\", \"美国\"),\n    FR(\"FR\", \"法国\"),\n    DE(\"DE\", \"德国\"),\n    IT(\"IT\", \"意大利\"),\n    ES(\"ES\", \"西班牙\"),\n    GB(\"GB\", \"英国\"),\n    HK(\"HK\", \"中国香港\");"
                code:
                  type: string
                  description: 银行编号
                name:
                  type: string
                  description: 银行名称
                branchName:
                  type: string
                  description: 支行名称
                address:
                  type: string
                  description: 银行地址
                prcptcd:
                  type: string
                  description: 大额行号
                province:
                  type: string
                  description: 银行省份
                city:
                  type: string
                  description: 银行城市
                bindType:
                  type: string
                  description: 对公、对私
                cardNumber:
                  type: string
                  description: 银行卡号
                accountPhone:
                  type: string
                  description: 关联手机号
                accountName:
                  type: string
                  description: 账户名称
                currencys:
                  type: array
                  description: 币种
                  items: {}
                extAccountId:
                  type: string
                  description: 外部单号
              required:
                - cardType
                - userType
                - region
                - name
                - address
                - bindType
                - cardNumber
                - accountPhone
                - accountName
                - currencys
                - extAccountId
    get:
      summary: GET payees bank account
      operationId: get-payees
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/payee-bank-account.v1.yaml
      description: 查询收款人信息
      requestBody:
        description: ''
      parameters:
        - schema:
            type: string
          in: query
          name: payeeBankAccountId
          required: true
          description: 收款人银行卡账户号
    delete:
      summary: DELETE payee bank account
      operationId: delete-payees
      description: 删除收款人
      requestBody: {}
      parameters:
        - schema:
            type: string
          in: query
          name: payeeBankAccountId
          required: true
          description: 收款人银行卡账户号
    parameters: []
  /batch-payments:
    get:
      summary: GET batch payments
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/batch-pay.v1.yaml
      operationId: get-pays
      description: 付款记录查询
      requestBody: {}
      parameters:
        - schema:
            type: string
          in: query
          name: batchId
          required: true
    post:
      summary: POST create batch payment
      operationId: post-pays
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/batch-pay.v1.yaml
      description: 创建付款指令
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                batchId:
                  type: string
                  description: 外部批次号
                list:
                  type:
                    - array
                  description: 请求对象
                  items:
                    type: object
                    properties:
                      tradeCode:
                        type: string
                        description: 贸易编码
                      payeeBankAccountNumber:
                        type: string
                        description: 收款人银行卡号，用于校验
                      paymentId:
                        type: string
                        description: 外部唯一单号
                      sourceCurrency:
                        type: string
                        description: 源币种
                      targetCurrency:
                        type: string
                        description: 目标币种
                      targetAmount:
                        type: string
                        description: 目标金额
                      tradeDate:
                        type: string
                        default: yyyy-MM-dd
                        description: 交易时间
                        format: date
                      goodsName:
                        type: string
                        description: 商品名称
                      goodsNumber:
                        type: string
                        description: 商品数量
                      goodsPrice:
                        type: string
                        description: 商品单价
                      logistics:
                        type: string
                        description: 物流方式
                      procurementYype:
                        type: string
                        description: 采购类型
                      payeeBankAccountId:
                        type: string
                        description: 收款人编号
                    required:
                      - tradeCode
                      - payeeBankAccountNumber
                      - paymentId
                      - sourceCurrency
                      - targetCurrency
                      - targetAmount
                      - tradeDate
                      - goodsName
                      - goodsNumber
                      - goodsPrice
                      - logistics
                      - procurementYype
                      - payeeBankAccountId
                verificationCode:
                  type: string
                  description: 短信验证码
              required:
                - batchId
        description: ''
    parameters: []
  /verification-codes:
    post:
      summary: POST verification codes
      operationId: post-verification-codes
      responses:
        '200':
          description: OK
      description: 发送短信验证码
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  description: 'SUPPLIER_PAYMENT("供应商付款")'
  '/batch-payments/{batchId}/payments':
    parameters:
      - schema:
          type: string
        name: batchId
        in: path
        required: true
    get:
      summary: GET payments
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                  list:
                    type: array
                    items:
                      $ref: ./models/payment.v1.yaml
      operationId: get-batch-pays-extBatchId
      description: 批次详情
      requestBody:
        description: ''
      parameters:
        - schema:
            type: string
          in: query
          name: paymentId
        - schema:
            type: integer
            maximum: 100
            minimum: 1
          in: query
          name: pageSize
          required: true
          description: 分页大小
        - schema:
            type: integer
            maximum: 0
            minimum: 1
          in: query
          name: pageNum
          required: true
          description: 页码
  /payee-document:
    put:
      summary: PUT payee account document
      operationId: put-payee-document
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                payeeBankAccountId:
                  type: string
                  description: 外部收款人银行账户id
                attatchmentId:
                  type: string
                  description: 附件id
        description: ''
      description: 更新材料信息
components:
  schemas: {}
  securitySchemes:
    Authorization:
      name: Developer Token
      type: apiKey
      in: query
